apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - otel-collector.yaml
  - jaeger.yaml

patches:
  - path: order-service-patch.yaml
  - path: shipping-service-patch.yaml
  - path: inventory-service-patch.yaml

namespace: default 